# Generated by Django 4.2.6 on 2023-11-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0010_remove_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='cutecat.jpeg', null=True, upload_to=''),
        ),
    ]
