# Generated by Django 4.2.6 on 2023-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0012_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Accepted', 'Order Accepted')], max_length=200, null=True),
        ),
    ]
