# Generated by Django 4.2.6 on 2023-11-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0016_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
    ]
