# Generated by Django 4.2.6 on 2023-11-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0017_remove_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
